### ISSUE TITLE
Clean up TODO's in scheduler affinity revamp

### ISSUE THREAD

**Issue by ispeters** [facebookexperimental/libunifex#528]
At the very least, I need to work out what the `blocking_kind` and `is_always_scheduler_affine` properties are for `retry_when`.  Other things:
- [ ] figure out what to do with `let_value_with_stop_source` because it leaks the ability to request stop from a random *Scheduler*
- [ ] customize `with_scheduler_affinity` for most/all algorithms
- [ ] probably other things…
